/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cumimpactsa;

import static cumimpactsa.MappingProject.grid;
import static cumimpactsa.MappingProject.processing;
import static cumimpactsa.MappingProject.processingProgressPercent;
import static cumimpactsa.MappingProject.sensitivityScores;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author ast
 */
public class MainWindow extends javax.swing.JFrame {

    
    private DrawableData drawingPaneShows = null;
    
    //TODO: Create SwingWorkers for all time-intensive tasks here. Add to main window.
    

    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() 
    {
        
        initComponents();
        
        ButtonGroup group = new ButtonGroup();
        group.add(this.radioButtonProcessedLayer);
        group.add(this.radioButtonRawLayer);
        
        MappingProject.initializeProcessors();
        
        //progressBar.setVisible(false);
        progressBar.setMinimum(0);
        progressBar.setMaximum(100);
      
        //progressBar.setStringPainted(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listEcocomps = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listStressors = new javax.swing.JList();
        labelStressors = new javax.swing.JLabel();
        labelEcologicalComponents = new javax.swing.JLabel();
        drawingPane = new javax.swing.JPanel();
        buttonStressorsPlus = new javax.swing.JButton();
        buttonStressorsMinus = new javax.swing.JButton();
        buttonEcoPlus = new javax.swing.JButton();
        buttonEcoMinus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listResults = new javax.swing.JList();
        radioButtonRawLayer = new javax.swing.JRadioButton();
        radioButtonProcessedLayer = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        buttonResultsMinus = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        menuBarMain = new javax.swing.JMenuBar();
        menuProject = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuLoad = new javax.swing.JMenuItem();
        menuProcessing = new javax.swing.JMenu();
        menuSensitivityscores = new javax.swing.JMenuItem();
        menuPreprocessing = new javax.swing.JMenuItem();
        MenuView = new javax.swing.JMenu();
        menuColorScale = new javax.swing.JMenuItem();
        menuDiversityIndexAvg = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuStressorIndex = new javax.swing.JMenuItem();
        menuWeightedStressorIndex = new javax.swing.JMenuItem();
        menuImpactIndex = new javax.swing.JMenuItem();
        menuImpactIndex1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemAreaPlots = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ImpactMapper");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ResizedHandler(evt);
            }
        });

        listEcocomps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listEcocompsMouseClicked(evt);
            }
        });
        listEcocomps.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listEcocompsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listEcocomps);

        listStressors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listStressorsMouseClicked(evt);
            }
        });
        listStressors.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listStressorsValueChanged(evt);
            }
        });
        listStressors.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                StressorListChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listStressors);

        labelStressors.setText("Stressors");

        labelEcologicalComponents.setText("Ecological components");

        drawingPane.setBackground(new java.awt.Color(204, 204, 204));
        drawingPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        drawingPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                drawingPaneComponentResized(evt);
            }
        });

        org.jdesktop.layout.GroupLayout drawingPaneLayout = new org.jdesktop.layout.GroupLayout(drawingPane);
        drawingPane.setLayout(drawingPaneLayout);
        drawingPaneLayout.setHorizontalGroup(
            drawingPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        drawingPaneLayout.setVerticalGroup(
            drawingPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        buttonStressorsPlus.setText("+");
        buttonStressorsPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStressorsPlusActionPerformed(evt);
            }
        });

        buttonStressorsMinus.setText("-");
        buttonStressorsMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStressorsMinusActionPerformed(evt);
            }
        });

        buttonEcoPlus.setText("+");
        buttonEcoPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEcoPlusActionPerformed(evt);
            }
        });

        buttonEcoMinus.setText("-");
        buttonEcoMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEcoMinusActionPerformed(evt);
            }
        });

        jLabel2.setText("Results");

        listResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listResultsMouseClicked(evt);
            }
        });
        listResults.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listResultsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listResults);

        radioButtonRawLayer.setSelected(true);
        radioButtonRawLayer.setText("Selected data (raw)");
        radioButtonRawLayer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonRawLayerStateChanged(evt);
            }
        });
        radioButtonRawLayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonRawLayerActionPerformed(evt);
            }
        });

        radioButtonProcessedLayer.setText("Selected data (processed)");
        radioButtonProcessedLayer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonProcessedLayerStateChanged(evt);
            }
        });
        radioButtonProcessedLayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonProcessedLayerActionPerformed(evt);
            }
        });

        jLabel1.setText("Display content");

        buttonResultsMinus.setText("-");
        buttonResultsMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResultsMinusActionPerformed(evt);
            }
        });

        progressBar.setBackground(new java.awt.Color(51, 153, 0));
        progressBar.setForeground(new java.awt.Color(51, 153, 0));
        progressBar.setString("\"No processing\"");

        menuProject.setText("Project");

        menuNew.setText("New");
        menuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewActionPerformed(evt);
            }
        });
        menuProject.add(menuNew);

        menuSave.setText("Save...");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menuProject.add(menuSave);

        menuLoad.setText("Load...");
        menuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoadActionPerformed(evt);
            }
        });
        menuProject.add(menuLoad);

        menuBarMain.add(menuProject);

        menuProcessing.setText("Processing & data");

        menuSensitivityscores.setText("Sensitivity scores...");
        menuSensitivityscores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSensitivityscoresActionPerformed(evt);
            }
        });
        menuProcessing.add(menuSensitivityscores);

        menuPreprocessing.setText("Pre-processing...");
        menuPreprocessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPreprocessingActionPerformed(evt);
            }
        });
        menuProcessing.add(menuPreprocessing);

        menuBarMain.add(menuProcessing);

        MenuView.setText("View");

        menuColorScale.setText("Color scale....");
        menuColorScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColorScaleActionPerformed(evt);
            }
        });
        MenuView.add(menuColorScale);

        menuBarMain.add(MenuView);

        menuDiversityIndexAvg.setText("Analysis");

        jMenu1.setText("Indices");

        jMenuItem1.setText("Ecological diversity index...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuStressorIndex.setText("Stressor index (unweighted)...");
        menuStressorIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStressorIndexActionPerformed(evt);
            }
        });
        jMenu1.add(menuStressorIndex);

        menuWeightedStressorIndex.setText("Stressor index (weighted)");
        menuWeightedStressorIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWeightedStressorIndexActionPerformed(evt);
            }
        });
        jMenu1.add(menuWeightedStressorIndex);

        menuImpactIndex.setText("Impact index (sum)...");
        menuImpactIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImpactIndexActionPerformed(evt);
            }
        });
        jMenu1.add(menuImpactIndex);

        menuImpactIndex1.setText("Impact index (avg)...");
        menuImpactIndex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImpactIndex1ActionPerformed(evt);
            }
        });
        jMenu1.add(menuImpactIndex1);

        menuDiversityIndexAvg.add(jMenu1);

        jMenu2.setText("Stressors");

        menuItemAreaPlots.setText("High-diversity area plots");
        menuItemAreaPlots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAreaPlotsActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemAreaPlots);

        menuDiversityIndexAvg.add(jMenu2);

        menuBarMain.add(menuDiversityIndexAvg);

        setJMenuBar(menuBarMain);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelStressors)
                            .add(labelEcologicalComponents)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 269, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 269, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(buttonStressorsPlus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(buttonStressorsMinus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(buttonEcoPlus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(buttonEcoMinus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 269, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(buttonResultsMinus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(drawingPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(layout.createSequentialGroup()
                                .add(radioButtonRawLayer)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(radioButtonProcessedLayer)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(249, 249, 249))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, progressBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(9, 9, 9)
                        .add(jLabel3)
                        .add(2, 2, 2)
                        .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(drawingPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(radioButtonRawLayer)
                            .add(radioButtonProcessedLayer))
                        .add(3, 3, 3))
                    .add(layout.createSequentialGroup()
                        .add(labelStressors)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(labelEcologicalComponents)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                            .add(layout.createSequentialGroup()
                                .add(buttonStressorsPlus)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(buttonStressorsMinus)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(buttonEcoPlus)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(buttonEcoMinus)
                                .add(120, 120, 120)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(buttonResultsMinus)
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Shows new project window
     * @param evt 
     */
    private void menuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewActionPerformed
       
        //clear data
        MappingProject.reset();
        //clear graphics
        drawingPane.getGraphics().setColor(Color.BLACK);
        drawingPane.getGraphics().fillRect(0, 0, drawingPane.getWidth(), drawingPane.getHeight());
        //drawingPane.update(null);
        //remove data layer names from lists
        String[] ecocompNames=MappingProject.getEcocompNames();
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<ecocompNames.length; i++) {model.addElement(ecocompNames[i]);}
        this.listEcocomps.setModel(model);
        String[] stressorNames=MappingProject.getStressorNames();
        model = new DefaultListModel();
        for(int i=0; i<stressorNames.length; i++) {model.addElement(stressorNames[i]);}
        this.listStressors.setModel(model);
        String[] resultNames=MappingProject.getResultNames();
        model = new DefaultListModel();
        for(int i=0; i<resultNames.length; i++) {model.addElement(resultNames[i]);}
        this.listResults.setModel(model);
        
      
       
    }//GEN-LAST:event_menuNewActionPerformed

    private void updateGraphics()
    {
        if(MappingProject.grid!=null)
       {
           if(this.drawingPaneShows!=null)
           {
               ImageCreator creator = new ImageCreator(drawingPane.getWidth(), drawingPane.getHeight());
               BufferedImage image;
               if(this.radioButtonRawLayer.isSelected())
               {
                   image = drawingPaneShows.getImage(creator, false);
                   
               }
               else if(this.radioButtonProcessedLayer.isSelected())
               {
                   image = image = drawingPaneShows.getImage(creator, true);
               }
               else //something went wrong
               {
                   double[][] hasData=MappingProject.grid.isFilled();
                   image = creator.createStudyAreaImage(hasData, MappingProject.grid.getDimensions());
               } 
                drawingPane.getGraphics().drawImage(image, 0, 0, this);
                
               
           }
           else
           {
                double[][] hasData=MappingProject.grid.isFilled();
                ImageCreator creator = new ImageCreator(this.drawingPane.getWidth(),this.drawingPane.getHeight());
                BufferedImage image = creator.createStudyAreaImage(hasData, MappingProject.grid.getDimensions());
                drawingPane.getGraphics().drawImage(image, 0, 0, this);
           }    
           
       }
        
    }
    
    private void ResizedHandler(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ResizedHandler
     // updateGraphics(); NEVER CALLED
    }//GEN-LAST:event_ResizedHandler

    private void buttonStressorsPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStressorsPlusActionPerformed
        
        //show load data dialog
        LoadDataForm dialog = new LoadDataForm(this,true);
        dialog.setDataType(GlobalResources.DATATYPE_STRESSOR);
        dialog.setVisible(true);
        
        //update stressor list
        String[] stressorNames=MappingProject.getStressorNames();
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<stressorNames.length; i++) {model.addElement(stressorNames[i]);}
        this.listStressors.setModel(model);
        //this.update(null);
        
        //update graphics to show the latest stressor
        SpatialDataLayer newStressor = MappingProject.getLastDataAdded();
        drawingPaneShows=newStressor;
        updateGraphics();
       
    }//GEN-LAST:event_buttonStressorsPlusActionPerformed

    private void StressorListChanged(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_StressorListChanged
       
        //doesn't work - leave empty
       
           
    }//GEN-LAST:event_StressorListChanged

    private void listStressorsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listStressorsValueChanged
        
           String stressorName = (String) this.listStressors.getSelectedValue();
           SpatialDataLayer stressor=MappingProject.getStressorByName(stressorName);
           if(stressor!=null)
           {
              listEcocomps.clearSelection();
              listResults.clearSelection();
              drawingPaneShows = stressor;
              this.updateGraphics();  
       }
        
    }//GEN-LAST:event_listStressorsValueChanged

    private void buttonStressorsMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStressorsMinusActionPerformed
        String stressorName = (String) this.listStressors.getSelectedValue();
        MappingProject.removeStressorByName(stressorName);
        
        //update stressor list
         String[] stressorNames=MappingProject.getStressorNames();
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<stressorNames.length; i++) {model.addElement(stressorNames[i]);}
        this.listStressors.setModel(model);
        
        //update graphics (stop showing removed stressor)
        drawingPaneShows = null;
        updateGraphics();

    }//GEN-LAST:event_buttonStressorsMinusActionPerformed

    private void buttonEcoPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEcoPlusActionPerformed
        //show load data dialog
        LoadDataForm dialog = new LoadDataForm(this,true);
        dialog.setDataType(GlobalResources.DATATYPE_ECOCOMP);
        dialog.setVisible(true);
        
        //update stressor list
        String[] ecocompNames=MappingProject.getEcocompNames();
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<ecocompNames.length; i++) {model.addElement(ecocompNames[i]);}
        this.listEcocomps.setModel(model);
        //this.update(null);
        
        //update graphics to show the latest stressor
        SpatialDataLayer newEcocomp = MappingProject.getLastDataAdded();
        if(newEcocomp!=null)
        {
            drawingPaneShows = newEcocomp;  //so that it doesn't get lost on resize
            updateGraphics();

            
        }
    }//GEN-LAST:event_buttonEcoPlusActionPerformed

    private void listEcocompsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEcocompsValueChanged
         String ecocompName = (String) this.listEcocomps.getSelectedValue();
           SpatialDataLayer ecocomp=MappingProject.getEcocompByName(ecocompName);
           if(ecocomp!=null)
           {
      
               listStressors.clearSelection();
               listResults.clearSelection();
               drawingPaneShows = ecocomp;
               updateGraphics();

           }
         
    }//GEN-LAST:event_listEcocompsValueChanged

    private void listStressorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listStressorsMouseClicked
      //  listStressorsValueChanged(null);
    }//GEN-LAST:event_listStressorsMouseClicked

    private void listEcocompsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listEcocompsMouseClicked
        //listEcocompsValueChanged(null);
    }//GEN-LAST:event_listEcocompsMouseClicked

    private void buttonEcoMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEcoMinusActionPerformed
         String ecocompName = (String) this.listEcocomps.getSelectedValue();
        MappingProject.removeEcocompByName(ecocompName);
        
        //update stressor list
         String[] ecocompNames=MappingProject.getEcocompNames();
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<ecocompNames.length; i++) {model.addElement(ecocompNames[i]);}
        this.listEcocomps.setModel(model);
        
        //update graphics (stop showing removed ecocomp)
        drawingPaneShows = null;
        updateGraphics();

    }//GEN-LAST:event_buttonEcoMinusActionPerformed

    private void menuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoadActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(new File(GlobalResources.lastUsedFolder));
        int result = fileChooser.showOpenDialog(this);
      
        
        
        if (result == JFileChooser.APPROVE_OPTION)
        {

            File selectedFile = fileChooser.getSelectedFile();
            GlobalResources.lastUsedFolder=selectedFile.getParent();
            this.setResizable(false);
            this.setFocusable(false);
            this.progressBar.setValue(5);
            this.progressBar.update(progressBar.getGraphics());
            this.update(this.getGraphics());
            
            try
            {
                
               //  Path pathAbsolute = Paths.get("/var/data/stuff/xyz.dat");
      //  Path pathBase = Paths.get("/var/data");
       // Path pathRelative = pathBase.relativize(pathAbsolute);
        
                
                CsvTable table = new CsvTable();
                table.readFromFile(selectedFile);
                //StatusWindow statusWindow=new StatusWindow();
                //statusWindow.setText("Loading...");
                //statusWindow.setupProgressBar(0, 100);
                //statusWindow.setVisible(true);
                MappingProject.projectFolder=Paths.get(selectedFile.getAbsolutePath()).getParent().toString();
                MappingProject.createFromTable(table);
            
                while(MappingProject.processing)
                {
                    //System.out.println("Waiting for processing thread...");
                   //this.setEnabled(false);
                   //this.setFocusable(false);
                    //updateGraphics();
                    //statusWindow.setProgress(MappingProject.processingProgressPercent);
                    //statusWindow.setText("Loading project component: " + MappingProject.processingProgressPercent);
                    //statusWindow.update(statusWindow.getGraphics());
                    //this.setTitle("Loading project component " + MappingProject.processingProgressPercent);
                    progressBar.setValue(MappingProject.processingProgressPercent);

                    //progressBar.setString(MappingProject.processingProgressPercent + " %");
                    progressBar.update(progressBar.getGraphics());
                    //System.out.println("% complete: " + MappingProject.processingProgressPercent);
                    Thread.sleep(500);
                }
                
                //update GUI
                double[][] hasData=MappingProject.grid.isFilled();
                drawingPaneShows=null;
                updateGraphics();
              
                
                String[] stressorNames=MappingProject.getStressorNames();
                DefaultListModel model = new DefaultListModel();
                for(int i=0; i<stressorNames.length; i++) {model.addElement(stressorNames[i]);}
                this.listStressors.setModel(model);
                
                String[] ecocompNames=MappingProject.getEcocompNames();
                model = new DefaultListModel();
                for(int i=0; i<ecocompNames.length; i++) {model.addElement(ecocompNames[i]);}
                this.listEcocomps.setModel(model);
                
                updateResultsList();
                progressBar.setValue(0);
                progressBar.setString("Processing completed");
            }
            catch(Exception e)
            {
                MappingProject.reset(); //in case loading failed
                JOptionPane.showMessageDialog(null, "Could not load file. " + e.getMessage().toString() + e.getStackTrace().toString());
            }
            finally
            {
                MappingProject.processingProgressPercent=0;
                progressBar.setValue(0);
                this.setResizable(true);
                this.setFocusable(true);
                progressBar.setValue(0);
            }

            
        }
    }//GEN-LAST:event_menuLoadActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(new File(GlobalResources.lastUsedFolder));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = fileChooser.getSelectedFile();
            GlobalResources.lastUsedFolder=selectedFile.getParent();
            MappingProject.save(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuSensitivityscoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSensitivityscoresActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(new File(GlobalResources.lastUsedFolder));
        fileChooser.setName("Choose a sensitivity score CSV table");
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = fileChooser.getSelectedFile();
            GlobalResources.lastUsedFolder=selectedFile.getParent();
            MappingProject.sensitivityScores=new SensitivityScoreSet();
            MappingProject.sensitivityScores.createFromFile(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_menuSensitivityscoresActionPerformed

    private void menuPreprocessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPreprocessingActionPerformed

        ProcessingWindow dialog = new ProcessingWindow(this, true);
        dialog.setVisible(true);
        
        //set up all lists
        
    }//GEN-LAST:event_menuPreprocessingActionPerformed

    private void radioButtonRawLayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonRawLayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonRawLayerActionPerformed

    private void radioButtonRawLayerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonRawLayerStateChanged

        radioButtonProcessedLayerStateChanged(evt);
    }//GEN-LAST:event_radioButtonRawLayerStateChanged

    private void radioButtonProcessedLayerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonProcessedLayerStateChanged
        updateGraphics();
    }//GEN-LAST:event_radioButtonProcessedLayerStateChanged

    private void menuColorScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColorScaleActionPerformed
        ColorScaleDialog dialog = new ColorScaleDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuColorScaleActionPerformed

    private void updateResultsList()
    {
        String[] resultNames=MappingProject.getResultNames();
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<resultNames.length; i++) {model.addElement(resultNames[i]);}
        this.listResults.setModel(model);
        //this.update(null);
    }
    
    
    
    
    
    private void radioButtonProcessedLayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonProcessedLayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonProcessedLayerActionPerformed

    private void listResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listResultsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listResultsMouseClicked

    private void listResultsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listResultsValueChanged
         String resultName = (String) this.listResults.getSelectedValue();
           DrawableData result=MappingProject.getResultByName(resultName);
           if(result!=null)
           {
      
               listStressors.clearSelection();
               listEcocomps.clearSelection();
               drawingPaneShows = result;
               updateGraphics();
 
             
           }
    }//GEN-LAST:event_listResultsValueChanged

    private void buttonResultsMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResultsMinusActionPerformed
        String resultName = (String) this.listResults.getSelectedValue();
        MappingProject.removeResultByName(resultName);
        updateResultsList();
        drawingPaneShows = null;
        updateGraphics();
    }//GEN-LAST:event_buttonResultsMinusActionPerformed

    private void drawingPaneComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_drawingPaneComponentResized
        updateGraphics();
    }//GEN-LAST:event_drawingPaneComponentResized

    private void menuImpactIndex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImpactIndex1ActionPerformed
        //check if sensitivity scores exist
        if(MappingProject.sensitivityScores==null || MappingProject.sensitivityScores.size()<1)
        {
            JOptionPane.showMessageDialog(this,"To calculate an impact index, you must first load sensitivity scores.");
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(new File(GlobalResources.lastUsedFolder));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            final File selectedFile = fileChooser.getSelectedFile();
            GlobalResources.lastUsedFolder=selectedFile.getParent();
            
            //calculate index in worker thread
            MappingProject.processing=true;
            this.setFocusable(false);
            this.setResizable(false);
            this.progressBar.setValue(5);
            this.progressBar.update(progressBar.getGraphics());
            SwingWorker<ImpactIndex, Void> worker = new SwingWorker<ImpactIndex, Void>() 
            {
                 @Override
                 protected ImpactIndex doInBackground() throws Exception 
                 {
                    //System.out.println("**** Started background thread...");
                    ImpactIndex index = new ImpactIndex(selectedFile.getAbsolutePath(),MappingProject.sensitivityScores, true);
                    MappingProject.processing=false;
                    return index;
                }
                 
                 @Override 
                 protected void done()
                 {
                     //System.out.println("Background thread is done.");
                     MappingProject.processingProgressPercent=0;
                     try    
                     {
                        ImpactIndex index = get();
                     
                     }
                     catch(Exception e)
                     {
                         JOptionPane.showMessageDialog(null, "Error retriving results from diversity index calculation thread.");
                     }

                 }
            };
            try
            {
                worker.execute();

                //block whil processing, but update progress bar
                while(MappingProject.processing)
                {

                    //System.out.println("Main thread is waiting...");
                    progressBar.setValue(MappingProject.processingProgressPercent);
                    progressBar.update(progressBar.getGraphics());
                    Thread.sleep(500);

                }

                    Thread.sleep(100); //
                    ImpactIndex index = worker.get();
            
 
                //show in drawing pane;

                drawingPaneShows = index;
                updateGraphics();

                CsvTable table = MappingProject.grid.createTableFromLayer(index, false);
                table.writeToFile(selectedFile.getAbsolutePath());

                 //write contributions
                CsvTable cTable = index.getScores().getContributionsAsTable();
                String basepath;
                int pos=selectedFile.getAbsolutePath().lastIndexOf(".");
                if(pos<1) {basepath=selectedFile.getAbsolutePath();}
                 else {basepath = selectedFile.getAbsolutePath().substring(0,pos);}
                cTable.writeToFile(basepath+"_contributions.csv");

                MappingProject.results.add(index);
                updateResultsList();
            
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error retrieving unweighted stressor index from worker thread.");
            }
            finally
            {
                this.setResizable(true);
                this.setFocusable(true);
                MappingProject.processingProgressPercent=0;
                progressBar.setValue(0);
                updateGraphics();
            }

        }
    }//GEN-LAST:event_menuImpactIndex1ActionPerformed

    //impact index as sum
    private void menuImpactIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImpactIndexActionPerformed
        //check if sensitivity scores exist
        if(MappingProject.sensitivityScores==null || MappingProject.sensitivityScores.size()<1)
        {
            JOptionPane.showMessageDialog(this,"To calculate an impact index, you must first load sensitivity scores.");
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(new File(GlobalResources.lastUsedFolder));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            final File selectedFile = fileChooser.getSelectedFile();
            GlobalResources.lastUsedFolder=selectedFile.getParent();
            
            //calculate index in worker thread
            MappingProject.processing=true;
            this.setFocusable(false);
            this.setResizable(false);
            
            this.progressBar.setValue(5);
            this.progressBar.update(progressBar.getGraphics());
            
            SwingWorker<ImpactIndex, Void> worker = new SwingWorker<ImpactIndex, Void>() 
            {
                 @Override
                 protected ImpactIndex doInBackground() throws Exception 
                 {
                    //System.out.println("**** Started background thread...");
                    ImpactIndex index = new ImpactIndex(selectedFile.getAbsolutePath(),MappingProject.sensitivityScores, false);
                    MappingProject.processing=false;
                    return index;
                }
                 
                 @Override 
                 protected void done()
                 {
                     //System.out.println("Background thread is done.");
                     MappingProject.processingProgressPercent=0;
                     try    
                     {
                        ImpactIndex index = get();
                     
                     }
                     catch(Exception e)
                     {
                         JOptionPane.showMessageDialog(null, "Error retriving results from diversity index calculation thread.");
                     }

                 }
            };
            try
            {
                worker.execute();

                //block whil processing, but update progress bar
                while(MappingProject.processing)
                {

                    //System.out.println("Main thread is waiting...");
                    progressBar.setValue(MappingProject.processingProgressPercent);
                    progressBar.update(progressBar.getGraphics());
                    Thread.sleep(500);

                }

                    Thread.sleep(100); //
                    ImpactIndex index = worker.get();            
            
           
                //show in drawing pane;
                drawingPaneShows = index;
                updateGraphics();

                CsvTable table = MappingProject.grid.createTableFromLayer(index, false);
                table.writeToFile(selectedFile.getAbsolutePath());

                //write contributions
                CsvTable cTable = index.getScores().getContributionsAsTable();
                String basepath;
                int pos=selectedFile.getAbsolutePath().lastIndexOf(".");
                if(pos<1) {basepath=selectedFile.getAbsolutePath();}
                 else {basepath = selectedFile.getAbsolutePath().substring(0,pos);}
                cTable.writeToFile(basepath+"_contributions.csv");


                MappingProject.results.add(index);

                updateResultsList();
                
           }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error retrieving unweighted stressor index from worker thread.");
            }
            finally
            {
                this.setResizable(true);
                this.setFocusable(true);
                MappingProject.processingProgressPercent=0;
                progressBar.setValue(0);
                updateGraphics();
            }     
        }

    }//GEN-LAST:event_menuImpactIndexActionPerformed

    //weighted stressor index
    private void menuWeightedStressorIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWeightedStressorIndexActionPerformed
        //check if sensitivity scores exist
        if(MappingProject.sensitivityScores==null || MappingProject.sensitivityScores.size()<1)
        {
            JOptionPane.showMessageDialog(this,"To calculate a weighted stressor index, you must first load sensitivity scores.");
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(new File(GlobalResources.lastUsedFolder));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            final File selectedFile = fileChooser.getSelectedFile();
            GlobalResources.lastUsedFolder=selectedFile.getParent();
            
             //calculate index in worker thread
            MappingProject.processing=true;
            this.setFocusable(false);
            this.setResizable(false);
            this.progressBar.setValue(5);
            this.progressBar.update(progressBar.getGraphics());
            SwingWorker<WeightedStressorIndex, Void> worker = new SwingWorker<WeightedStressorIndex, Void>() 
            {
                 @Override
                 protected WeightedStressorIndex doInBackground() throws Exception 
                 {
                    //System.out.println("**** Started background thread...");
                    WeightedStressorIndex index = new WeightedStressorIndex(selectedFile.getAbsolutePath());
                    MappingProject.processing=false;
                    return index;
                }
                 
                 @Override 
                 protected void done()
                 {
                     //System.out.println("Background thread is done.");
                     
                     try    {
                        WeightedStressorIndex index = get();
                     }
                     catch(Exception e)
                     {
                         JOptionPane.showMessageDialog(null, "Error retriving results from diversity index calculation thread.");
                     }
                     MappingProject.processingProgressPercent=0;
                     
                 }
            };
            try
            {
                worker.execute();
                
                //block whil processing, but update progress bar
                while(MappingProject.processing)
                {

                    //System.out.println("Main thread is waiting...");
                    progressBar.setValue(MappingProject.processingProgressPercent);
                    progressBar.update(progressBar.getGraphics());
                    Thread.sleep(500);
                }
           
                Thread.sleep(100); //
                WeightedStressorIndex index = worker.get();
                 //show in drawing pane;
                drawingPaneShows = index;
                updateGraphics();

                MappingProject.results.add(index);
                updateResultsList();

                CsvTable table = MappingProject.grid.createTableFromLayer(index, false);
                table.writeToFile(selectedFile.getAbsolutePath());
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error retrieving unweighted stressor index from worker thread.");
            }
            finally
            {
                this.setResizable(true);
                this.setFocusable(true);
                MappingProject.processingProgressPercent=0;
                progressBar.setValue(0);
                updateGraphics();
            }
        }
    }//GEN-LAST:event_menuWeightedStressorIndexActionPerformed

    private void menuStressorIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStressorIndexActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(new File(GlobalResources.lastUsedFolder));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            final File selectedFile = fileChooser.getSelectedFile();
            GlobalResources.lastUsedFolder=selectedFile.getParent();
            
             //calculate index in worker thread
            MappingProject.processing=true;
            this.setFocusable(false);
            this.setResizable(false);
            this.progressBar.setValue(5);
            this.progressBar.update(progressBar.getGraphics());
            SwingWorker<StressorIndex, Void> worker = new SwingWorker<StressorIndex, Void>() 
            {
                 @Override
                 protected StressorIndex doInBackground() throws Exception 
                 {
                    //System.out.println("**** Started background thread...");
                    StressorIndex index = new StressorIndex(selectedFile.getAbsolutePath());
                    MappingProject.processing=false;
                    return index;
                }
                 
                 @Override 
                 protected void done()
                 {
                     //System.out.println("Background thread is done.");
                     
                     try    {
                        StressorIndex index = get();
                     }
                     catch(Exception e)
                     {
                         JOptionPane.showMessageDialog(null, "Error retriving results from diversity index calculation thread.");
                     }
                     MappingProject.processingProgressPercent=0;
                     
                 }
            };
            try
            {
                worker.execute();

                //block whil processing, but update progress bar
                while(MappingProject.processing)
                {

                    //System.out.println("Main thread is waiting...");
                    progressBar.setValue(MappingProject.processingProgressPercent);
                    progressBar.update(progressBar.getGraphics());
                    Thread.sleep(500);
                }
           
                Thread.sleep(100); //
                StressorIndex index = worker.get();
                //show in drawing pane;
                drawingPaneShows = index;
                updateGraphics();

                MappingProject.results.add(index);
                updateResultsList();

                CsvTable table = MappingProject.grid.createTableFromLayer(index, false);
                table.writeToFile(selectedFile.getAbsolutePath());
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error retrieving unweighted stressor index from worker thread.");
            }
            finally
            {
                this.setResizable(true);
                this.setFocusable(true);
                MappingProject.processingProgressPercent=0;
                progressBar.setValue(0);
                updateGraphics();
            }
            
        }
    }//GEN-LAST:event_menuStressorIndexActionPerformed

    //diversity index - refactoring failed thus the general name
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(new File(GlobalResources.lastUsedFolder));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            final File selectedFile = fileChooser.getSelectedFile();
            GlobalResources.lastUsedFolder=selectedFile.getParent();
            
            //calculate index in worker thread
            MappingProject.processing=true;
            this.setFocusable(false);
            this.setResizable(false);
            this.progressBar.setValue(5);
            this.progressBar.update(progressBar.getGraphics());
            SwingWorker<DiversityIndex, Void> worker = new SwingWorker<DiversityIndex, Void>() 
            {
                 @Override
                 protected DiversityIndex doInBackground() throws Exception 
                 {
                    System.out.println("**** Started background thread...");
                    DiversityIndex index = new DiversityIndex(selectedFile.getAbsolutePath());
                    MappingProject.processing=false;
                    return index;
                }
                 
                 @Override 
                 protected void done()
                 {
                     System.out.println("Background thread is done.");
                     
                     try    {
                        DiversityIndex index = get();
                     }
                     catch(Exception e)
                     {
                         JOptionPane.showMessageDialog(null, "Error retriving results from diversity index calculation thread.");
                     }
                     MappingProject.processingProgressPercent=0;
                     
                 }
            };
            try
            {
                worker.execute();

                //block whil processing, but update progress bar
                while(MappingProject.processing)
                {

                    System.out.println("Main thread is waiting...");
                    progressBar.setValue(MappingProject.processingProgressPercent);
                    progressBar.update(progressBar.getGraphics());
                    Thread.sleep(500);

                }


                    Thread.sleep(100); //
                    DiversityIndex index = worker.get();
                    //show in drawing pane;
                    drawingPaneShows = index;

                    CsvTable table = MappingProject.grid.createTableFromLayer(index, false);
                    table.writeToFile(selectedFile.getAbsolutePath());
                    MappingProject.processingProgressPercent=0;
                    MappingProject.results.add(index);
                    updateResultsList();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error retrieving results from worker thread for diversity index.");
            }
            finally
            {
                this.setResizable(true);
                this.setFocusable(true);
                MappingProject.processingProgressPercent=0;
                progressBar.setValue(0);
                updateGraphics();
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemAreaPlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAreaPlotsActionPerformed
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(new File(GlobalResources.lastUsedFolder));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            final File selectedFile = fileChooser.getSelectedFile();
            GlobalResources.lastUsedFolder=selectedFile.getParent();

            //calculation in worker thread
            MappingProject.processing=true;
            this.setFocusable(false);
            this.setResizable(false);
            SwingWorker<StressorAreaRelationships, Void> worker = new SwingWorker<StressorAreaRelationships, Void>() 
            {
                 @Override
                 protected StressorAreaRelationships doInBackground() throws Exception 
                 {
                    //System.out.println("**** Started background thread...");
                    StressorAreaRelationships output = new StressorAreaRelationships();
                    MappingProject.processing=false;
                    return output;
                }
                 
                 @Override 
                 protected void done()
                 {
                     //System.out.println("Background thread is done.");
                     
                     try    {
                        StressorAreaRelationships output = get();
                     }
                     catch(Exception e)
                     {
                         JOptionPane.showMessageDialog(null, "Error retriving results from diversity index calculation thread.");
                     }
                     MappingProject.processingProgressPercent=0;
                     
                 }
            };
            try
            {
                worker.execute();

                //block whil processing, but update progress bar
                while(MappingProject.processing)
                {

                    //System.out.println("Main thread is waiting...");
                    progressBar.setValue(MappingProject.processingProgressPercent);
                    progressBar.update(progressBar.getGraphics());
                    Thread.sleep(500);

                }

                Thread.sleep(100);
                StressorAreaRelationships output = worker.get();
                output.writeToFile(selectedFile.getAbsolutePath());
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error retrieving results from worker thread for stressor-area relationships.");
            }
            finally
            {
                this.setResizable(true);
                this.setFocusable(true);
                MappingProject.processingProgressPercent=0;
                progressBar.setValue(0);
                updateGraphics();
            }
        }
    }//GEN-LAST:event_menuItemAreaPlotsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuView;
    private javax.swing.JButton buttonEcoMinus;
    private javax.swing.JButton buttonEcoPlus;
    private javax.swing.JButton buttonResultsMinus;
    private javax.swing.JButton buttonStressorsMinus;
    private javax.swing.JButton buttonStressorsPlus;
    private javax.swing.JPanel drawingPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelEcologicalComponents;
    private javax.swing.JLabel labelStressors;
    private javax.swing.JList listEcocomps;
    private javax.swing.JList listResults;
    private javax.swing.JList listStressors;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenuItem menuColorScale;
    private javax.swing.JMenu menuDiversityIndexAvg;
    private javax.swing.JMenuItem menuImpactIndex;
    private javax.swing.JMenuItem menuImpactIndex1;
    private javax.swing.JMenuItem menuItemAreaPlots;
    private javax.swing.JMenuItem menuLoad;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JMenuItem menuPreprocessing;
    private javax.swing.JMenu menuProcessing;
    private javax.swing.JMenu menuProject;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSensitivityscores;
    private javax.swing.JMenuItem menuStressorIndex;
    private javax.swing.JMenuItem menuWeightedStressorIndex;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JRadioButton radioButtonProcessedLayer;
    private javax.swing.JRadioButton radioButtonRawLayer;
    // End of variables declaration//GEN-END:variables
}
